" Vim syntax file
" Language:		YamahaRT config
" Maintainer:	okkiroxx
" Last Change:	2016/7/9
" Credits:

setlocal iskeyword+=*,.,/,-

syn match	yamahaNumber	"\(\s\|,\|=\|-\|\[\)\@<=[0-9]\+\(\s\|,\|=\|\]\|/\|$\)\@="
syn match	yamahaString	\".*"\
syn match	yamahaTime		"[0-9]\{1,2}:[0-9]\{1,2}"
syn match	yamahaIPv4		"\d\{1,3}\.\d\{1,3}\.\d\{1,3}\.\d\{1,3}"
							\ nextgroup=yamahaSubnet
syn match	yamahaSubnet	"[0-9a-zA-Z]\@<=\/\d\{1,2}\(\s\|$\)\@="
syn match	yamahaEmail		"\S*@\S*"
syn match	yamahaURL		"\(\S\+\.\)\{1,}\S\+"
syn match	yamahaTunnel	"tunnel[0-9*]*"
syn match	yamahaVlan		"vlan[0-9*]*"
syn match	yamahaPP		"pp[0-9*]\+"
syn match	yamahaBRI		"bri[0-9*]\+\(\.[1-9]\)*"
syn match	yamahaPRI		"pri[0-9*]\+"
syn match	yamahaBridge	"bridge[0-9*]\+"
syn match	yamahaUSB		"usb[0-9*]\+"
syn match	yamahaBind		"\(\s\|,\)\@<=[0-9]\+-[0-9]\+\(\s\|,\|$\)\@="
syn match	yamahaSplitinto	"split-into-[1-9:]\+"
syn match	yamahaPort		"\(tcp\|udp\)\/[0-9]\+"
syn match	yamahaBandwidth	"\(\s\|=\|,\)\@<=[0-9]\+m"

syn match	yamahaComment	"^#.*$"


syn keyword yamahaNumber	.
syn keyword yamahaNumber	*


syn keyword	yamahaBuiltin	3des-cbc
syn keyword	yamahaBuiltin	admin
syn keyword	yamahaBuiltin	aes-cbc
syn keyword	yamahaBuiltin	all
syn keyword	yamahaBuiltin	anonymous
syn keyword	yamahaBuiltin	anti-replay-check
syn keyword	yamahaBuiltin	any
syn keyword	yamahaBuiltin	auth-error
syn keyword	yamahaBuiltin	auto
syn keyword	yamahaBuiltin	bandwidth
syn keyword	yamahaBuiltin	call-waiting
syn keyword	yamahaBuiltin	chap
syn keyword	yamahaBuiltin	client
syn keyword	yamahaBuiltin	connection
syn keyword	yamahaBuiltin	control
syn keyword	yamahaBuiltin	count
syn keyword	yamahaBuiltin	default
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+dhcp"
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+dns"
syn keyword	yamahaBuiltin	divide-network
syn keyword	yamahaBuiltin	dhcpc
syn keyword	yamahaBuiltin	dhcps
syn keyword	yamahaBuiltin	domain
syn keyword	yamahaBuiltin	dynamic
syn keyword	yamahaBuiltin	economy
syn keyword	yamahaBuiltin	enable
syn keyword	yamahaBuiltin	esp
syn keyword	yamahaBuiltin	established
syn keyword	yamahaBuiltin	except
syn keyword	yamahaBuiltin	filter
syn keyword	yamahaBuiltin	flets
syn keyword	yamahaBuiltin	fqdn
syn keyword	yamahaBuiltin	ftp
syn keyword	yamahaBuiltin	ftpdata
syn keyword	yamahaBuiltin	ftpdata-21
syn keyword	yamahaBuiltin	g711u
syn keyword	yamahaBuiltin	gateway
syn keyword	yamahaBuiltin	gre
syn keyword	yamahaBuiltin	group
syn keyword	yamahaBuiltin	heartbeat
syn keyword	yamahaBuiltin	high
syn keyword	yamahaBuiltin	host
syn keyword	yamahaBuiltin	http
syn keyword	yamahaBuiltin	https
syn keyword	yamahaBuiltin	hybrid
syn keyword	yamahaBuiltin	icmp
syn keyword	yamahaBuiltin	icmp6
syn keyword	yamahaBuiltin	icmp-echo
syn keyword	yamahaBuiltin	ident
syn keyword	yamahaBuiltin	ike
syn keyword	yamahaBuiltin	in
syn keyword	yamahaBuiltin	ir
syn keyword	yamahaBuiltin	include
syn keyword	yamahaBuiltin	ipudp
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+ip"
syn keyword	yamahaBuiltin	ipcp
syn keyword	yamahaBuiltin	isdn-ntt
syn keyword	yamahaBuiltin	isdn-terminal
syn keyword	yamahaBuiltin	join
syn keyword	yamahaBuiltin	keepalive
syn keyword	yamahaBuiltin	key
syn keyword	yamahaBuiltin	key-id
syn keyword	yamahaBuiltin	l128
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+l2tp"
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+l2tpv3"
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+l2tpv3-raw"
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+lan[1-9]*"
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+lan[1-9]\(\.\|:\)[1-9]"
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+line"
syn keyword	yamahaBuiltin	linkdown-recovery
syn keyword	yamahaBuiltin	local
syn keyword	yamahaBuiltin	low
syn keyword	yamahaBuiltin	masquerade
syn keyword	yamahaBuiltin	md5-hmac
syn keyword	yamahaBuiltin	mppe-any
syn keyword	yamahaBuiltin	mschap
syn keyword	yamahaBuiltin	mschap-v2
syn keyword	yamahaBuiltin	name
syn match	yamahaBuiltin	"netbios_ns"
syn match	yamahaBuiltin	"netbios_ssn"
syn match	yamahaBuiltin	"netbios_dgm"
syn keyword	yamahaBuiltin	netmeeting
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+ngn"
syn keyword	yamahaBuiltin	nntp
syn keyword	yamahaBuiltin	none
syn keyword	yamahaBuiltin	normal
syn keyword	yamahaBuiltin	normal-number
syn keyword	yamahaBuiltin	ntp
syn keyword	yamahaBuiltin	ntpdate
syn keyword	yamahaBuiltin	ntt
syn keyword	yamahaBuiltin	off
syn keyword	yamahaBuiltin	o_flag
syn keyword	yamahaBuiltin	on
syn keyword	yamahaBuiltin	ospf
syn keyword	yamahaBuiltin	out
syn keyword	yamahaBuiltin	pap
syn keyword	yamahaBuiltin	pass
syn keyword	yamahaBuiltin	pass-log
syn keyword	yamahaBuiltin	pass-nolog
syn keyword	yamahaBuiltin	plain
syn keyword	yamahaBuiltin	pop3
syn keyword	yamahaBuiltin	pool
syn keyword	yamahaBuiltin	port
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+pp\(\s\|$\)\@="
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+pptp"
syn keyword	yamahaBuiltin	precedence
syn keyword	yamahaBuiltin	prefix
syn keyword	yamahaBuiltin	priority
syn keyword	yamahaBuiltin	primary
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+provider"
syn keyword	yamahaBuiltin	public
syn keyword	yamahaBuiltin	recieve
syn keyword	yamahaBuiltin	recursive
syn keyword	yamahaBuiltin	reject
syn keyword	yamahaBuiltin	reject-nolog
syn keyword	yamahaBuiltin	remain-silent
syn keyword	yamahaBuiltin	retry-interval
syn keyword	yamahaBuiltin	restrict
syn keyword	yamahaBuiltin	route
syn keyword	yamahaBuiltin	route-table
syn keyword	yamahaBuiltin	router
syn keyword	yamahaBuiltin	routing
syn keyword	yamahaBuiltin	server
syn keyword	yamahaBuiltin	sha
syn keyword	yamahaBuiltin	sha-hmac
syn keyword	yamahaBuiltin	shaping
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+sip"
syn keyword	yamahaBuiltin	smtp
syn keyword	yamahaBuiltin	smtp-auth
syn keyword	yamahaBuiltin	static
syn keyword	yamahaBuiltin	static-pass
syn keyword	yamahaBuiltin	static-pass-log
syn keyword	yamahaBuiltin	static-pass-nolog
syn keyword	yamahaBuiltin	submission
syn keyword	yamahaBuiltin	switch-interface
syn keyword	yamahaBuiltin	switch-router
syn match	yamahaBuiltin	"\(^\s*\)\@!\s\+syslog"
syn keyword	yamahaBuiltin	tel
syn keyword	yamahaBuiltin	tel-key
syn keyword	yamahaBuiltin	telnet
syn keyword	yamahaBuiltin	tcp
syn keyword	yamahaBuiltin	tcpfin
syn keyword	yamahaBuiltin	tcpflag
syn keyword	yamahaBuiltin	tcprst
syn keyword	yamahaBuiltin	text
syn keyword	yamahaBuiltin	traffic
syn keyword	yamahaBuiltin	trigger
syn keyword	yamahaBuiltin	udp
syn keyword	yamahaBuiltin	vid
syn keyword	yamahaBuiltin	version
syn keyword	yamahaBuiltin	weight
syn keyword	yamahaBuiltin	www


syn match	yamahaCommand		"^\s*administrator"
syn match	yamahaCommand		"^\s*administrator password"
syn match	yamahaCommand		"^\s*administrator password encrypted"
syn match	yamahaCommand		"^\s*administrator radius auth"
syn match	yamahaCommand		"^\s*alarm batch"
syn match	yamahaCommand		"^\s*alarm connection data"
syn match	yamahaCommand		"^\s*alarm entire"
syn match	yamahaCommand		"^\s*alarm http revision-up"
syn match	yamahaCommand		"^\s*alarm lua"
syn match	yamahaCommand		"^\s*alarm mobile"
syn match	yamahaCommand		"^\s*alarm sd"
syn match	yamahaCommand		"^\s*alarm startup"
syn match	yamahaCommand		"^\s*alarm usbhost"
syn match	yamahaCommand		"^\s*alarm usbhost"
syn match	yamahaCommand		"^\s*analog call"
syn match	yamahaCommand		"^\s*analog extension dial prefix"
syn match	yamahaCommand		"^\s*analog extension emergency-call-dial type"
syn match	yamahaCommand		"^\s*analog local address"
syn match	yamahaCommand		"^\s*analog supplementary-service pseudo"
syn match	yamahaCommand		"^\s*ap config directory"
syn match	yamahaCommand		"^\s*ap config filename"
syn match	yamahaCommand		"^\s*ap control config delete"
syn match	yamahaCommand		"^\s*ap control config get"
syn match	yamahaCommand		"^\s*ap control config set"
syn match	yamahaCommand		"^\s*ap control config-auto-set use"
syn match	yamahaCommand		"^\s*ap control firmware update go"
syn match	yamahaCommand		"^\s*ap control http proxy timeout"
syn match	yamahaCommand		"^\s*ap control http proxy use"
syn match	yamahaCommand		"^\s*ap select"
syn match	yamahaCommand		"^\s*auth user"
syn match	yamahaCommand		"^\s*auth user attribute"
syn match	yamahaCommand		"^\s*auth user group"
syn match	yamahaCommand		"^\s*auth user group attribute"
syn match	yamahaCommand		"^\s*bgp aggregate"
syn match	yamahaCommand		"^\s*bgp aggregate filter"
syn match	yamahaCommand		"^\s*bgp autonomous-system"
syn match	yamahaCommand		"^\s*bgp configure refresh"
syn match	yamahaCommand		"^\s*bgp export"
syn match	yamahaCommand		"^\s*bgp export aspath"
syn match	yamahaCommand		"^\s*bgp export filter"
syn match	yamahaCommand		"^\s*bgp import"
syn match	yamahaCommand		"^\s*bgp import filter"
syn match	yamahaCommand		"^\s*bgp log"
syn match	yamahaCommand		"^\s*bgp neighbor"
syn match	yamahaCommand		"^\s*bgp preference"
syn match	yamahaCommand		"^\s*bgp router id"
syn match	yamahaCommand		"^\s*bgp use"
syn match	yamahaCommand		"^\s*bridge learning"
syn match	yamahaCommand		"^\s*bridge learning .* static"
syn match	yamahaCommand		"^\s*bridge learning .* timer"
syn match	yamahaCommand		"^\s*bridge member"
syn match	yamahaCommand		"^\s*clear account"
syn match	yamahaCommand		"^\s*clear account mobile"
syn match	yamahaCommand		"^\s*clear account ngn data"
syn match	yamahaCommand		"^\s*clear account pp"
syn match	yamahaCommand		"^\s*clear arp"
syn match	yamahaCommand		"^\s*clear boot list"
syn match	yamahaCommand		"^\s*clear bridge learning"
syn match	yamahaCommand		"^\s*clear dns cache"
syn match	yamahaCommand		"^\s*clear external-memory syslog"
syn match	yamahaCommand		"^\s*clear heartbeat2"
syn match	yamahaCommand		"^\s*clear ip dynamic routing"
syn match	yamahaCommand		"^\s*clear ipv6 dynamic routing"
syn match	yamahaCommand		"^\s*clear ipv6 neighbor cache"
syn match	yamahaCommand		"^\s*clear log"
syn match	yamahaCommand		"^\s*clear mobile access limitation"
syn match	yamahaCommand		"^\s*clear mobile access limitation pp"
syn match	yamahaCommand		"^\s*clear nat descriptor dynamic"
syn match	yamahaCommand		"^\s*clear nat descriptor interface dynamic pp"
syn match	yamahaCommand		"^\s*clear nat descriptor interface dynamic tunnel"
syn match	yamahaCommand		"^\s*clear nat descriptor interface dynamic wan1"
syn match	yamahaCommand		"^\s*clear nat descriptor interface dynamic"
syn match	yamahaCommand		"^\s*clear status pp"
syn match	yamahaCommand		"^\s*clear status tunnel"
syn match	yamahaCommand		"^\s*clear status wan1"
syn match	yamahaCommand		"^\s*clear status"
syn match	yamahaCommand		"^\s*clear switching-hub macaddress"
syn match	yamahaCommand		"^\s*clear url filter"
syn match	yamahaCommand		"^\s*cold start"
syn match	yamahaCommand		"^\s*connect"
syn match	yamahaCommand		"^\s*console character"
syn match	yamahaCommand		"^\s*console columns"
syn match	yamahaCommand		"^\s*console info"
syn match	yamahaCommand		"^\s*console lines"
syn match	yamahaCommand		"^\s*console prompt"
syn match	yamahaCommand		"^\s*cooperation bandwidth-measuring"
syn match	yamahaCommand		"^\s*cooperation bandwidth-measuring go"
syn match	yamahaCommand		"^\s*cooperation bandwidth-measuring remote"
syn match	yamahaCommand		"^\s*cooperation load-watch"
syn match	yamahaCommand		"^\s*cooperation load-watch control"
syn match	yamahaCommand		"^\s*cooperation load-watch go"
syn match	yamahaCommand		"^\s*cooperation load-watch remote"
syn match	yamahaCommand		"^\s*cooperation load-watch trigger"
syn match	yamahaCommand		"^\s*cooperation port"
syn match	yamahaCommand		"^\s*copy"
syn match	yamahaCommand		"^\s*copy config"
syn match	yamahaCommand		"^\s*copy exec"
syn match	yamahaCommand		"^\s*date"
syn match	yamahaCommand		"^\s*dashboard accumulate"
syn match	yamahaCommand		"^\s*delete"
syn match	yamahaCommand		"^\s*delete config"
syn match	yamahaCommand		"^\s*description"
syn match	yamahaCommand		"^\s*description pp"
syn match	yamahaCommand		"^\s*description tunnel"
syn match	yamahaCommand		"^\s*description wan1"
syn match	yamahaCommand		"^\s*description"
syn match	yamahaCommand		"^\s*dhcp client client-identifier"
syn match	yamahaCommand		"^\s*dhcp client hostname"
syn match	yamahaCommand		"^\s*dhcp client option"
syn match	yamahaCommand		"^\s*dhcp client release linkdown"
syn match	yamahaCommand		"^\s*dhcp convert"
syn match	yamahaCommand		"^\s*dhcp duplicate check"
syn match	yamahaCommand		"^\s*dhcp manual lease"
syn match	yamahaCommand		"^\s*dhcp manual release"
syn match	yamahaCommand		"^\s*dhcp relay select"
syn match	yamahaCommand		"^\s*dhcp relay server"
syn match	yamahaCommand		"^\s*dhcp relay threshold"
syn match	yamahaCommand		"^\s*dhcp scope"
syn match	yamahaCommand		"^\s*dhcp scope bind"
syn match	yamahaCommand		"^\s*dhcp scope lease type"
syn match	yamahaCommand		"^\s*dhcp scope option"
syn match	yamahaCommand		"^\s*dhcp server"
syn match	yamahaCommand		"^\s*dhcp server rfc2131 compliant"
syn match	yamahaCommand		"^\s*dhcp service"
syn match	yamahaCommand		"^\s*disconnect"
syn match	yamahaCommand		"^\s*disconnect ip connection"
syn match	yamahaCommand		"^\s*disconnect ipv6 connection"
syn match	yamahaCommand		"^\s*disconnect user"
syn match	yamahaCommand		"^\s*dns cache max entry"
syn match	yamahaCommand		"^\s*dns cache use"
syn match	yamahaCommand		"^\s*dns domain"
syn match	yamahaCommand		"^\s*dns host"
syn match	yamahaCommand		"^\s*dns notice order"
syn match	yamahaCommand		"^\s*dns private address spoof"
syn match	yamahaCommand		"^\s*dns private name"
syn match	yamahaCommand		"^\s*dns server"
syn match	yamahaCommand		"^\s*dns server dhcp"
syn match	yamahaCommand		"^\s*dns server pp"
syn match	yamahaCommand		"^\s*dns server select"
syn match	yamahaCommand		"^\s*dns service"
syn match	yamahaCommand		"^\s*dns service fallback"
syn match	yamahaCommand		"^\s*dns srcport"
syn match	yamahaCommand		"^\s*dns static"
syn match	yamahaCommand		"^\s*dns syslog resolv"
syn match	yamahaCommand		"^\s*ethernet filter"
syn match	yamahaCommand		"^\s*ethernet .* filter"
syn match	yamahaCommand		"^\s*execute at-command"
syn match	yamahaCommand		"^\s*execute batch"
syn match	yamahaCommand		"^\s*exit"
syn match	yamahaCommand		"^\s*external-memory accelerator cache size"
syn match	yamahaCommand		"^\s*external-memory auto-search time"
syn match	yamahaCommand		"^\s*external-memory batch filename"
syn match	yamahaCommand		"^\s*external-memory boot permit"
syn match	yamahaCommand		"^\s*external-memory boot timeout"
syn match	yamahaCommand		"^\s*external-memory cache mode"
syn match	yamahaCommand		"^\s*external-memory config filename"
syn match	yamahaCommand		"^\s*external-memory exec filename"
syn match	yamahaCommand		"^\s*external-memory performance-test go"
syn match	yamahaCommand		"^\s*external-memory syslog filename"
syn match	yamahaCommand		"^\s*grep"
syn match	yamahaCommand		"^\s*heartbeat pre-shared-key"
syn match	yamahaCommand		"^\s*heartbeat receive"
syn match	yamahaCommand		"^\s*heartbeat send"
syn match	yamahaCommand		"^\s*heartbeat2 myname"
syn match	yamahaCommand		"^\s*heartbeat2 receive"
syn match	yamahaCommand		"^\s*heartbeat2 receive enable"
syn match	yamahaCommand		"^\s*heartbeat2 receive log"
syn match	yamahaCommand		"^\s*heartbeat2 receive monitor"
syn match	yamahaCommand		"^\s*heartbeat2 receive record limit"
syn match	yamahaCommand		"^\s*heartbeat2 transmit"
syn match	yamahaCommand		"^\s*heartbeat2 transmit enable"
syn match	yamahaCommand		"^\s*heartbeat2 transmit interval"
syn match	yamahaCommand		"^\s*heartbeat2 transmit log"
syn match	yamahaCommand		"^\s*help"
syn match	yamahaCommand		"^\s*http revision-down permit"
syn match	yamahaCommand		"^\s*http revision-up go"
syn match	yamahaCommand		"^\s*http revision-up permit"
syn match	yamahaCommand		"^\s*http revision-up proxy"
syn match	yamahaCommand		"^\s*http revision-up schedule"
syn match	yamahaCommand		"^\s*http revision-up timeout"
syn match	yamahaCommand		"^\s*http revision-up url"
syn match	yamahaCommand		"^\s*httpd custom-gui api password"
syn match	yamahaCommand		"^\s*httpd custom-gui api use"
syn match	yamahaCommand		"^\s*httpd custom-gui use"
syn match	yamahaCommand		"^\s*httpd custom-gui user"
syn match	yamahaCommand		"^\s*httpd host"
syn match	yamahaCommand		"^\s*httpd listen"
syn match	yamahaCommand		"^\s*httpd service"
syn match	yamahaCommand		"^\s*httpd timeout"
syn match	yamahaCommand		"^\s*interface reset"
syn match	yamahaCommand		"^\s*ip arp timer"
syn match	yamahaCommand		"^\s*ip filter"
syn match	yamahaCommand		"^\s*ip filter directed-broadcast"
syn match	yamahaCommand		"^\s*ip filter dynamic"
syn match	yamahaCommand		"^\s*ip filter dynamic timer"
syn match	yamahaCommand		"^\s*ip filter set"
syn match	yamahaCommand		"^\s*ip filter source-route"
syn match	yamahaCommand		"^\s*ip flow timer"
syn match	yamahaCommand		"^\s*ip forward filter"
syn match	yamahaCommand		"^\s*ip fragment remove df-bit"
syn match	yamahaCommand		"^\s*ip host"
syn match	yamahaCommand		"^\s*ip icmp echo-reply send"
syn match	yamahaCommand		"^\s*ip icmp echo-reply send-only-linkup"
syn match	yamahaCommand		"^\s*ip icmp error-decrypted-ipsec send"
syn match	yamahaCommand		"^\s*ip icmp log"
syn match	yamahaCommand		"^\s*ip icmp mask-reply send"
syn match	yamahaCommand		"^\s*ip icmp parameter-problem send"
syn match	yamahaCommand		"^\s*ip icmp redirect receive"
syn match	yamahaCommand		"^\s*ip icmp redirect send"
syn match	yamahaCommand		"^\s*ip icmp time-exceeded send"
syn match	yamahaCommand		"^\s*ip icmp timestamp-reply send"
syn match	yamahaCommand		"^\s*ip icmp unreachable send"
syn match	yamahaCommand		"^\s*ip implicit-route preference"
syn match	yamahaCommand		"^\s*ip inbound filter"
syn match	yamahaCommand		"^\s*ip keepalive"
syn match	yamahaCommand		"^\s*ip v*lan[1-9]\(/[1-9]\)* address"
syn match	yamahaCommand		"^\s*ip v*lan[1-9]\(/[1-9]\)* proxyarp"
syn match	yamahaCommand		"^\s*ip v*lan[1-9]\(/[1-9]\)* secure filter"
syn match	yamahaCommand		"^\s*ip local forward filter"
syn match	yamahaCommand		"^\s*ip loopback1 address"
syn match	yamahaCommand		"^\s*ip loopback1 ospf area"
syn match	yamahaCommand		"^\s*ip loopback1 secure filter"
syn match	yamahaCommand		"^\s*ip loopback2 address"
syn match	yamahaCommand		"^\s*ip loopback2 ospf area"
syn match	yamahaCommand		"^\s*ip loopback2 secure filter"
syn match	yamahaCommand		"^\s*ip loopback3 address"
syn match	yamahaCommand		"^\s*ip loopback3 ospf area"
syn match	yamahaCommand		"^\s*ip loopback3 secure filter"
syn match	yamahaCommand		"^\s*ip loopback4 address"
syn match	yamahaCommand		"^\s*ip loopback4 ospf area"
syn match	yamahaCommand		"^\s*ip loopback4 secure filter"
syn match	yamahaCommand		"^\s*ip loopback5 address"
syn match	yamahaCommand		"^\s*ip loopback5 ospf area"
syn match	yamahaCommand		"^\s*ip loopback5 secure filter"
syn match	yamahaCommand		"^\s*ip loopback6 address"
syn match	yamahaCommand		"^\s*ip loopback6 ospf area"
syn match	yamahaCommand		"^\s*ip loopback6 secure filter"
syn match	yamahaCommand		"^\s*ip loopback7 address"
syn match	yamahaCommand		"^\s*ip loopback7 ospf area"
syn match	yamahaCommand		"^\s*ip loopback7 secure filter"
syn match	yamahaCommand		"^\s*ip loopback8 address"
syn match	yamahaCommand		"^\s*ip loopback8 ospf area"
syn match	yamahaCommand		"^\s*ip loopback8 secure filter"
syn match	yamahaCommand		"^\s*ip loopback9 address"
syn match	yamahaCommand		"^\s*ip loopback9 ospf area"
syn match	yamahaCommand		"^\s*ip loopback9 secure filter"
syn match	yamahaCommand		"^\s*ip null secure filter"
syn match	yamahaCommand		"^\s*ip policy address group"
syn match	yamahaCommand		"^\s*ip policy filter"
syn match	yamahaCommand		"^\s*ip policy filter set"
syn match	yamahaCommand		"^\s*ip policy interface group"
syn match	yamahaCommand		"^\s*ip policy service"
syn match	yamahaCommand		"^\s*ip policy service group"
syn match	yamahaCommand		"^\s*ip pp address"
syn match	yamahaCommand		"^\s*ip pp forward filter"
syn match	yamahaCommand		"^\s*ip pp inbound filter list"
syn match	yamahaCommand		"^\s*ip pp intrusion detection"
syn match	yamahaCommand		"^\s*ip pp intrusion detection notice-interval"
syn match	yamahaCommand		"^\s*ip pp intrusion detection repeat-control"
syn match	yamahaCommand		"^\s*ip pp intrusion detection report"
syn match	yamahaCommand		"^\s*ip pp intrusion detection threshold"
syn match	yamahaCommand		"^\s*ip pp mtu"
syn match	yamahaCommand		"^\s*ip pp nat descriptor"
syn match	yamahaCommand		"^\s*ip pp ospf area"
syn match	yamahaCommand		"^\s*ip pp ospf neighbor"
syn match	yamahaCommand		"^\s*ip pp rebound"
syn match	yamahaCommand		"^\s*ip pp remote address"
syn match	yamahaCommand		"^\s*ip pp remote address pool"
syn match	yamahaCommand		"^\s*ip pp rip auth key"
syn match	yamahaCommand		"^\s*ip pp rip auth type"
syn match	yamahaCommand		"^\s*ip pp rip backup interface"
syn match	yamahaCommand		"^\s*ip pp rip connect interval"
syn match	yamahaCommand		"^\s*ip pp rip connect send"
syn match	yamahaCommand		"^\s*ip pp rip disconnect interval"
syn match	yamahaCommand		"^\s*ip pp rip disconnect send"
syn match	yamahaCommand		"^\s*ip pp rip filter"
syn match	yamahaCommand		"^\s*ip pp rip force-to-advertise"
syn match	yamahaCommand		"^\s*ip pp rip hold routing"
syn match	yamahaCommand		"^\s*ip pp rip hop"
syn match	yamahaCommand		"^\s*ip pp rip receive"
syn match	yamahaCommand		"^\s*ip pp rip send"
syn match	yamahaCommand		"^\s*ip pp rip trust gateway"
syn match	yamahaCommand		"^\s*ip pp secure filter"
syn match	yamahaCommand		"^\s*ip pp tcp mss limit"
syn match	yamahaCommand		"^\s*ip route"
syn match	yamahaCommand		"^\s*ip route change log"
syn match	yamahaCommand		"^\s*ip routing"
syn match	yamahaCommand		"^\s*ip routing process"
syn match	yamahaCommand		"^\s*ip simple-service"
syn match	yamahaCommand		"^\s*ip stealth"
syn match	yamahaCommand		"^\s*ip tos supersede"
syn match	yamahaCommand		"^\s*ip tunnel address"
syn match	yamahaCommand		"^\s*ip tunnel forward filter"
syn match	yamahaCommand		"^\s*ip tunnel intrusion detection"
syn match	yamahaCommand		"^\s*ip tunnel intrusion detection notice-interval"
syn match	yamahaCommand		"^\s*ip tunnel intrusion detection repeat-control"
syn match	yamahaCommand		"^\s*ip tunnel intrusion detection report"
syn match	yamahaCommand		"^\s*ip tunnel intrusion detection threshold"
syn match	yamahaCommand		"^\s*ip tunnel mtu"
syn match	yamahaCommand		"^\s*ip tunnel nat descriptor"
syn match	yamahaCommand		"^\s*ip tunnel ospf area"
syn match	yamahaCommand		"^\s*ip tunnel ospf neighbor"
syn match	yamahaCommand		"^\s*ip tunnel rebound"
syn match	yamahaCommand		"^\s*ip tunnel remote address"
syn match	yamahaCommand		"^\s*ip tunnel rip auth key"
syn match	yamahaCommand		"^\s*ip tunnel rip auth type"
syn match	yamahaCommand		"^\s*ip tunnel rip filter"
syn match	yamahaCommand		"^\s*ip tunnel rip force-to-advertise"
syn match	yamahaCommand		"^\s*ip tunnel rip hop"
syn match	yamahaCommand		"^\s*ip tunnel rip receive"
syn match	yamahaCommand		"^\s*ip tunnel rip send"
syn match	yamahaCommand		"^\s*ip tunnel rip trust gateway"
syn match	yamahaCommand		"^\s*ip tunnel secure filter"
syn match	yamahaCommand		"^\s*ip tunnel tcp mss limit"
syn match	yamahaCommand		"^\s*ip wan1 address"
syn match	yamahaCommand		"^\s*ip wan1 dhcp lease time"
syn match	yamahaCommand		"^\s*ip wan1 dhcp retry"
syn match	yamahaCommand		"^\s*ip wan1 forward filter"
syn match	yamahaCommand		"^\s*ip wan1 intrusion detection"
syn match	yamahaCommand		"^\s*ip wan1 intrusion detection notice-interval"
syn match	yamahaCommand		"^\s*ip wan1 intrusion detection repeat-control"
syn match	yamahaCommand		"^\s*ip wan1 intrusion detection report"
syn match	yamahaCommand		"^\s*ip wan1 intrusion detection threshold"
syn match	yamahaCommand		"^\s*ip wan1 mtu"
syn match	yamahaCommand		"^\s*ip wan1 nat descriptor"
syn match	yamahaCommand		"^\s*ip wan1 secure filter"
syn match	yamahaCommand		"^\s*ip wan1 tcp mss limit"
syn match	yamahaCommand		"^\s*ip bridge[1-9] address"
syn match	yamahaCommand		"^\s*ip .* arp log"
syn match	yamahaCommand		"^\s*ip .* arp queue length"
syn match	yamahaCommand		"^\s*ip .* arp static"
syn match	yamahaCommand		"^\s*ip .* forward filter"
syn match	yamahaCommand		"^\s*ip .* intrusion detection"
syn match	yamahaCommand		"^\s*ip .* intrusion detection notice-interval"
syn match	yamahaCommand		"^\s*ip .* intrusion detection repeat-control"
syn match	yamahaCommand		"^\s*ip .* intrusion detection report"
syn match	yamahaCommand		"^\s*ip .* intrusion detection threshold"
syn match	yamahaCommand		"^\s*ip .* mtu"
syn match	yamahaCommand		"^\s*ip .* nat descriptor"
syn match	yamahaCommand		"^\s*ip .* ospf area"
syn match	yamahaCommand		"^\s*ip .* ospf neighbor"
syn match	yamahaCommand		"^\s*ip .* rebound"
syn match	yamahaCommand		"^\s*ip .* rip auth key"
syn match	yamahaCommand		"^\s*ip .* rip auth type"
syn match	yamahaCommand		"^\s*ip .* rip filter"
syn match	yamahaCommand		"^\s*ip .* rip force-to-advertise"
syn match	yamahaCommand		"^\s*ip .* rip hop"
syn match	yamahaCommand		"^\s*ip .* rip receive"
syn match	yamahaCommand		"^\s*ip .* rip send"
syn match	yamahaCommand		"^\s*ip .* rip trust gateway"
syn match	yamahaCommand		"^\s*ip .* secondary address"
syn match	yamahaCommand		"^\s*ip .* tcp mss limit"
syn match	yamahaCommand		"^\s*ip .* vrrp"
syn match	yamahaCommand		"^\s*ip .* vrrp shutdown trigger"
syn match	yamahaCommand		"^\s*ip .* wol relay"
syn match	yamahaCommand		"^\s*ip .* dhcp lease time"
syn match	yamahaCommand		"^\s*ip .* dhcp retry"
syn match	yamahaCommand		"^\s*ip .* proxyarp"
syn match	yamahaCommand		"^\s*ip .* secure filter"
syn match	yamahaCommand		"^\s*ipsec auto refresh"
syn match	yamahaCommand		"^\s*ipsec ike always-on"
syn match	yamahaCommand		"^\s*ipsec ike auth method"
syn match	yamahaCommand		"^\s*ipsec ike backward-compatibility"
syn match	yamahaCommand		"^\s*ipsec ike duration"
syn match	yamahaCommand		"^\s*ipsec ike eap myname"
syn match	yamahaCommand		"^\s*ipsec ike eap request"
syn match	yamahaCommand		"^\s*ipsec ike eap send certreq"
syn match	yamahaCommand		"^\s*ipsec ike encryption"
syn match	yamahaCommand		"^\s*ipsec ike esp-encapsulation"
syn match	yamahaCommand		"^\s*ipsec ike group"
syn match	yamahaCommand		"^\s*ipsec ike hash"
syn match	yamahaCommand		"^\s*ipsec ike keepalive log"
syn match	yamahaCommand		"^\s*ipsec ike keepalive use"
syn match	yamahaCommand		"^\s*ipsec ike local address"
syn match	yamahaCommand		"^\s*ipsec ike local id"
syn match	yamahaCommand		"^\s*ipsec ike local name"
syn match	yamahaCommand		"^\s*ipsec ike log"
syn match	yamahaCommand		"^\s*ipsec ike message-id-control"
syn match	yamahaCommand		"^\s*ipsec ike mode-cfg address"
syn match	yamahaCommand		"^\s*ipsec ike mode-cfg address pool"
syn match	yamahaCommand		"^\s*ipsec ike mode-cfg method"
syn match	yamahaCommand		"^\s*ipsec ike nat-traversal"
syn match	yamahaCommand		"^\s*ipsec ike negotiate-strictly"
syn match	yamahaCommand		"^\s*ipsec ike payload type"
syn match	yamahaCommand		"^\s*ipsec ike pfs"
syn match	yamahaCommand		"^\s*ipsec ike pki file"
syn match	yamahaCommand		"^\s*ipsec ike pre-shared-key"
syn match	yamahaCommand		"^\s*ipsec ike proposal-limitation"
syn match	yamahaCommand		"^\s*ipsec ike queue length"
syn match	yamahaCommand		"^\s*ipsec ike remote address"
syn match	yamahaCommand		"^\s*ipsec ike remote id"
syn match	yamahaCommand		"^\s*ipsec ike remote name"
syn match	yamahaCommand		"^\s*ipsec ike restrict-dangling-sa"
syn match	yamahaCommand		"^\s*ipsec ike retry"
syn match	yamahaCommand		"^\s*ipsec ike send info"
syn match	yamahaCommand		"^\s*ipsec ike version"
syn match	yamahaCommand		"^\s*ipsec ike xauth myname"
syn match	yamahaCommand		"^\s*ipsec ike xauth request"
syn match	yamahaCommand		"^\s*ipsec ipcomp type"
syn match	yamahaCommand		"^\s*ipsec log illegal-spi"
syn match	yamahaCommand		"^\s*ipsec refresh sa"
syn match	yamahaCommand		"^\s*ipsec sa delete"
syn match	yamahaCommand		"^\s*ipsec sa policy"
syn match	yamahaCommand		"^\s*ipsec transport"
syn match	yamahaCommand		"^\s*ipsec transport template"
syn match	yamahaCommand		"^\s*ipsec tunnel"
syn match	yamahaCommand		"^\s*ipsec tunnel fastpath-fragment-function follow df-bit"
syn match	yamahaCommand		"^\s*ipsec tunnel outer df-bit"
syn match	yamahaCommand		"^\s*ipsec use"
syn match	yamahaCommand		"^\s*ipv6 filter"
syn match	yamahaCommand		"^\s*ipv6 filter dynamic"
syn match	yamahaCommand		"^\s*ipv6 icmp echo-reply send"
syn match	yamahaCommand		"^\s*ipv6 icmp echo-reply send-only-linkup"
syn match	yamahaCommand		"^\s*ipv6 icmp error-decrypted-ipsec send"
syn match	yamahaCommand		"^\s*ipv6 icmp log"
syn match	yamahaCommand		"^\s*ipv6 icmp packet-too-big send"
syn match	yamahaCommand		"^\s*ipv6 icmp parameter-problem send"
syn match	yamahaCommand		"^\s*ipv6 icmp redirect receive"
syn match	yamahaCommand		"^\s*ipv6 icmp redirect send"
syn match	yamahaCommand		"^\s*ipv6 icmp time-exceeded send"
syn match	yamahaCommand		"^\s*ipv6 icmp unreachable send"
syn match	yamahaCommand		"^\s*ipv6 lan[1-9] address"
syn match	yamahaCommand		"^\s*ipv6 lan[1-9] mld router version"
syn match	yamahaCommand		"^\s*ipv6 lan[1-9] mld host version"
syn match	yamahaCommand		"^\s*ipv6 lan[1-9] rtadv send"
syn match	yamahaCommand		"^\s*ipv6 loopback1 address"
syn match	yamahaCommand		"^\s*ipv6 loopback1 secure filter"
syn match	yamahaCommand		"^\s*ipv6 loopback2 address"
syn match	yamahaCommand		"^\s*ipv6 loopback2 secure filter"
syn match	yamahaCommand		"^\s*ipv6 loopback3 address"
syn match	yamahaCommand		"^\s*ipv6 loopback3 secure filter"
syn match	yamahaCommand		"^\s*ipv6 loopback4 address"
syn match	yamahaCommand		"^\s*ipv6 loopback4 secure filter"
syn match	yamahaCommand		"^\s*ipv6 loopback5 address"
syn match	yamahaCommand		"^\s*ipv6 loopback5 secure filter"
syn match	yamahaCommand		"^\s*ipv6 loopback6 address"
syn match	yamahaCommand		"^\s*ipv6 loopback6 secure filter"
syn match	yamahaCommand		"^\s*ipv6 loopback7 address"
syn match	yamahaCommand		"^\s*ipv6 loopback7 secure filter"
syn match	yamahaCommand		"^\s*ipv6 loopback8 address"
syn match	yamahaCommand		"^\s*ipv6 loopback8 secure filter"
syn match	yamahaCommand		"^\s*ipv6 loopback9 address"
syn match	yamahaCommand		"^\s*ipv6 loopback9 secure filter"
syn match	yamahaCommand		"^\s*ipv6 max auto address"
syn match	yamahaCommand		"^\s*ipv6 nd ns-trigger-dad"
syn match	yamahaCommand		"^\s*ipv6 null secure filter"
syn match	yamahaCommand		"^\s*ipv6 ospf area"
syn match	yamahaCommand		"^\s*ipv6 ospf area network"
syn match	yamahaCommand		"^\s*ipv6 ospf configure refresh"
syn match	yamahaCommand		"^\s*ipv6 ospf export filter"
syn match	yamahaCommand		"^\s*ipv6 ospf export from"
syn match	yamahaCommand		"^\s*ipv6 ospf import filter"
syn match	yamahaCommand		"^\s*ipv6 ospf import from"
syn match	yamahaCommand		"^\s*ipv6 ospf log"
syn match	yamahaCommand		"^\s*ipv6 ospf preference"
syn match	yamahaCommand		"^\s*ipv6 ospf router id"
syn match	yamahaCommand		"^\s*ipv6 ospf use"
syn match	yamahaCommand		"^\s*ipv6 ospf virtual-link"
syn match	yamahaCommand		"^\s*ipv6 pp address"
syn match	yamahaCommand		"^\s*ipv6 pp dad retry count"
syn match	yamahaCommand		"^\s*ipv6 pp dhcp service"
syn match	yamahaCommand		"^\s*ipv6 pp mld"
syn match	yamahaCommand		"^\s*ipv6 pp mld static"
syn match	yamahaCommand		"^\s*ipv6 pp mtu"
syn match	yamahaCommand		"^\s*ipv6 pp ospf area"
syn match	yamahaCommand		"^\s*ipv6 pp prefix"
syn match	yamahaCommand		"^\s*ipv6 pp prefix change log"
syn match	yamahaCommand		"^\s*ipv6 pp rip connect interval"
syn match	yamahaCommand		"^\s*ipv6 pp rip connect send"
syn match	yamahaCommand		"^\s*ipv6 pp rip disconnect interval"
syn match	yamahaCommand		"^\s*ipv6 pp rip disconnect send"
syn match	yamahaCommand		"^\s*ipv6 pp rip filter"
syn match	yamahaCommand		"^\s*ipv6 pp rip hold routing"
syn match	yamahaCommand		"^\s*ipv6 pp rip hop"
syn match	yamahaCommand		"^\s*ipv6 pp rip receive"
syn match	yamahaCommand		"^\s*ipv6 pp rip send"
syn match	yamahaCommand		"^\s*ipv6 pp rip trust gateway"
syn match	yamahaCommand		"^\s*ipv6 pp rtadv send"
syn match	yamahaCommand		"^\s*ipv6 pp secure filter"
syn match	yamahaCommand		"^\s*ipv6 pp tcp mss limit"
syn match	yamahaCommand		"^\s*ipv6 prefix"
syn match	yamahaCommand		"^\s*ipv6 rh0 discard"
syn match	yamahaCommand		"^\s*ipv6 rip preference"
syn match	yamahaCommand		"^\s*ipv6 rip use"
syn match	yamahaCommand		"^\s*ipv6 route"
syn match	yamahaCommand		"^\s*ipv6 routing"
syn match	yamahaCommand		"^\s*ipv6 routing process"
syn match	yamahaCommand		"^\s*ipv6 source address selection rule"
syn match	yamahaCommand		"^\s*ipv6 stealth"
syn match	yamahaCommand		"^\s*ipv6 tunnel address"
syn match	yamahaCommand		"^\s*ipv6 tunnel dhcp service"
syn match	yamahaCommand		"^\s*ipv6 tunnel mld"
syn match	yamahaCommand		"^\s*ipv6 tunnel mld static"
syn match	yamahaCommand		"^\s*ipv6 tunnel ospf area"
syn match	yamahaCommand		"^\s*ipv6 tunnel prefix"
syn match	yamahaCommand		"^\s*ipv6 tunnel prefix change log"
syn match	yamahaCommand		"^\s*ipv6 tunnel rip filter"
syn match	yamahaCommand		"^\s*ipv6 tunnel rip receive"
syn match	yamahaCommand		"^\s*ipv6 tunnel rip send"
syn match	yamahaCommand		"^\s*ipv6 tunnel secure filter"
syn match	yamahaCommand		"^\s*ipv6 tunnel tcp mss limit"
syn match	yamahaCommand		"^\s*ipv6 .* dhcp service"
syn match	yamahaCommand		"^\s*ipv6 .* mld"
syn match	yamahaCommand		"^\s*ipv6 .* mld static"
syn match	yamahaCommand		"^\s*ipv6 .* mtu"
syn match	yamahaCommand		"^\s*ipv6 .* ospf area"
syn match	yamahaCommand		"^\s*ipv6 .* rip filter"
syn match	yamahaCommand		"^\s*ipv6 .* rip hop"
syn match	yamahaCommand		"^\s*ipv6 .* rip receive"
syn match	yamahaCommand		"^\s*ipv6 .* rip send"
syn match	yamahaCommand		"^\s*ipv6 .* rip trust gateway"
syn match	yamahaCommand		"^\s*ipv6 .* rtadv send"
syn match	yamahaCommand		"^\s*ipv6 .* tcp mss limit"
syn match	yamahaCommand		"^\s*ipv6 .* vrrp"
syn match	yamahaCommand		"^\s*ipv6 .* vrrp shutdown trigger"
syn match	yamahaCommand		"^\s*ipv6 .* address"
syn match	yamahaCommand		"^\s*ipv6 .* dad retry count"
syn match	yamahaCommand		"^\s*ipv6 .* prefix"
syn match	yamahaCommand		"^\s*ipv6 .* prefix change log"
syn match	yamahaCommand		"^\s*ipv6 .* secure filter"
syn match	yamahaCommand		"^\s*isdn remote address call"
syn match	yamahaCommand		"^\s*isdn local address"
syn match	yamahaCommand		"^\s*l2tp always-on"
syn match	yamahaCommand		"^\s*l2tp hostname"
syn match	yamahaCommand		"^\s*l2tp keepalive log"
syn match	yamahaCommand		"^\s*l2tp keepalive use"
syn match	yamahaCommand		"^\s*l2tp local router-id"
syn match	yamahaCommand		"^\s*l2tp remote end-id"
syn match	yamahaCommand		"^\s*l2tp remote router-id"
syn match	yamahaCommand		"^\s*l2tp service"
syn match	yamahaCommand		"^\s*l2tp syslog"
syn match	yamahaCommand		"^\s*l2tp tunnel auth"
syn match	yamahaCommand		"^\s*l2tp tunnel disconnect time"
syn match	yamahaCommand		"^\s*lan backup recovery time"
syn match	yamahaCommand		"^\s*lan backup"
syn match	yamahaCommand		"^\s*lan count-hub-overflow"
syn match	yamahaCommand		"^\s*lan keepalive interval"
syn match	yamahaCommand		"^\s*lan keepalive log"
syn match	yamahaCommand		"^\s*lan keepalive use"
syn match	yamahaCommand		"^\s*lan linkup send-wait-time"
syn match	yamahaCommand		"^\s*lan port-mirroring lan1"
syn match	yamahaCommand		"^\s*lan shutdown"
syn match	yamahaCommand		"^\s*lan type"
syn match	yamahaCommand		"^\s*lan type lan[1-9] port-based-option"
syn match	yamahaCommand		"^\s*less"
syn match	yamahaCommand		"^\s*less config"
syn match	yamahaCommand		"^\s*less config list"
syn match	yamahaCommand		"^\s*less config pp"
syn match	yamahaCommand		"^\s*less config tunnel"
syn match	yamahaCommand		"^\s*less exec list"
syn match	yamahaCommand		"^\s*less file list"
syn match	yamahaCommand		"^\s*less log"
syn match	yamahaCommand		"^\s*line type"
syn match	yamahaCommand		"^\s*login password"
syn match	yamahaCommand		"^\s*login password encrypted"
syn match	yamahaCommand		"^\s*login radius use"
syn match	yamahaCommand		"^\s*login timer"
syn match	yamahaCommand		"^\s*login user"
syn match	yamahaCommand		"^\s*lua"
syn match	yamahaCommand		"^\s*lua use"
syn match	yamahaCommand		"^\s*luac"
syn match	yamahaCommand		"^\s*mail notify"
syn match	yamahaCommand		"^\s*mail notify status exec"
syn match	yamahaCommand		"^\s*mail server name"
syn match	yamahaCommand		"^\s*mail server pop"
syn match	yamahaCommand		"^\s*mail server smtp"
syn match	yamahaCommand		"^\s*mail server timeout"
syn match	yamahaCommand		"^\s*mail template"
syn match	yamahaCommand		"^\s*make directory"
syn match	yamahaCommand		"^\s*mobile access limit connection length"
syn match	yamahaCommand		"^\s*mobile access limit connection time"
syn match	yamahaCommand		"^\s*mobile access limit duration"
syn match	yamahaCommand		"^\s*mobile access limit length"
syn match	yamahaCommand		"^\s*mobile access limit time"
syn match	yamahaCommand		"^\s*mobile access-point name"
syn match	yamahaCommand		"^\s*mobile auto connect"
syn match	yamahaCommand		"^\s*mobile call prohibit auth-error count"
syn match	yamahaCommand		"^\s*mobile dial number"
syn match	yamahaCommand		"^\s*mobile disconnect input time"
syn match	yamahaCommand		"^\s*mobile disconnect output time"
syn match	yamahaCommand		"^\s*mobile disconnect time"
syn match	yamahaCommand		"^\s*mobile display caller id"
syn match	yamahaCommand		"^\s*mobile pin code usb1"
syn match	yamahaCommand		"^\s*mobile signal-strength"
syn match	yamahaCommand		"^\s*mobile signal-strength go"
syn match	yamahaCommand		"^\s*mobile syslog"
syn match	yamahaCommand		"^\s*mobile use"
syn match	yamahaCommand		"^\s*nat descriptor address inner"
syn match	yamahaCommand		"^\s*nat descriptor address outer"
syn match	yamahaCommand		"^\s*nat descriptor ftp port"
syn match	yamahaCommand		"^\s*nat descriptor log"
syn match	yamahaCommand		"^\s*nat descriptor masquerade incoming"
syn match	yamahaCommand		"^\s*nat descriptor masquerade port range"
syn match	yamahaCommand		"^\s*nat descriptor masquerade remove df-bit"
syn match	yamahaCommand		"^\s*nat descriptor masquerade rlogin"
syn match	yamahaCommand		"^\s*nat descriptor masquerade session limit"
syn match	yamahaCommand		"^\s*nat descriptor masquerade static"
syn match	yamahaCommand		"^\s*nat descriptor masquerade unconvertible port"
syn match	yamahaCommand		"^\s*nat descriptor sip"
syn match	yamahaCommand		"^\s*nat descriptor static"
syn match	yamahaCommand		"^\s*nat descriptor timer"
syn match	yamahaCommand		"^\s*nat descriptor type"
syn match	yamahaCommand		"^\s*netvolante-dns auto hostname pp"
syn match	yamahaCommand		"^\s*netvolante-dns auto hostname wan1"
syn match	yamahaCommand		"^\s*netvolante-dns auto hostname"
syn match	yamahaCommand		"^\s*netvolante-dns auto save"
syn match	yamahaCommand		"^\s*netvolante-dns delete go pp"
syn match	yamahaCommand		"^\s*netvolante-dns delete go wan1"
syn match	yamahaCommand		"^\s*netvolante-dns delete go"
syn match	yamahaCommand		"^\s*netvolante-dns get hostname list"
syn match	yamahaCommand		"^\s*netvolante-dns go pp"
syn match	yamahaCommand		"^\s*netvolante-dns go wan1"
syn match	yamahaCommand		"^\s*netvolante-dns go"
syn match	yamahaCommand		"^\s*netvolante-dns hostname host pp"
syn match	yamahaCommand		"^\s*netvolante-dns hostname host wan1"
syn match	yamahaCommand		"^\s*netvolante-dns hostname host"
syn match	yamahaCommand		"^\s*netvolante-dns port"
syn match	yamahaCommand		"^\s*netvolante-dns register timer"
syn match	yamahaCommand		"^\s*netvolante-dns retry interval pp"
syn match	yamahaCommand		"^\s*netvolante-dns retry interval wan1"
syn match	yamahaCommand		"^\s*netvolante-dns retry interval"
syn match	yamahaCommand		"^\s*netvolante-dns server"
syn match	yamahaCommand		"^\s*netvolante-dns server update address port"
syn match	yamahaCommand		"^\s*netvolante-dns server update address use"
syn match	yamahaCommand		"^\s*netvolante-dns set hostname pp"
syn match	yamahaCommand		"^\s*netvolante-dns set hostname wan1"
syn match	yamahaCommand		"^\s*netvolante-dns set hostname"
syn match	yamahaCommand		"^\s*netvolante-dns timeout pp"
syn match	yamahaCommand		"^\s*netvolante-dns timeout wan1"
syn match	yamahaCommand		"^\s*netvolante-dns timeout"
syn match	yamahaCommand		"^\s*netvolante-dns use pp"
syn match	yamahaCommand		"^\s*netvolante-dns use wan1"
syn match	yamahaCommand		"^\s*netvolante-dns use"
syn match	yamahaCommand		"^\s*ngn radius account callee"
syn match	yamahaCommand		"^\s*ngn radius account caller"
syn match	yamahaCommand		"^\s*ngn radius auth password"
syn match	yamahaCommand		"^\s*ngn type"
syn match	yamahaCommand		"^\s*nslookup"
syn match	yamahaCommand		"^\s*ntp backward-compatibility"
syn match	yamahaCommand		"^\s*ntp local address"
syn match	yamahaCommand		"^\s*ntpdate"
syn match	yamahaCommand		"^\s*operation button function download"
syn match	yamahaCommand		"^\s*operation execute batch permit"
syn match	yamahaCommand		"^\s*operation external-memory download permit"
syn match	yamahaCommand		"^\s*operation http revision-up permit"
syn match	yamahaCommand		"^\s*ospf area"
syn match	yamahaCommand		"^\s*ospf area network"
syn match	yamahaCommand		"^\s*ospf area stubhost"
syn match	yamahaCommand		"^\s*ospf configure refresh"
syn match	yamahaCommand		"^\s*ospf export filter"
syn match	yamahaCommand		"^\s*ospf export from"
syn match	yamahaCommand		"^\s*ospf import filter"
syn match	yamahaCommand		"^\s*ospf import from"
syn match	yamahaCommand		"^\s*ospf log"
syn match	yamahaCommand		"^\s*ospf merge equal cost stub"
syn match	yamahaCommand		"^\s*ospf preference"
syn match	yamahaCommand		"^\s*ospf router id"
syn match	yamahaCommand		"^\s*ospf use"
syn match	yamahaCommand		"^\s*ospf virtual-link"
syn match	yamahaCommand		"^\s*packetdump pp"
syn match	yamahaCommand		"^\s*packetdump wan1"
syn match	yamahaCommand		"^\s*packetdump"
syn match	yamahaCommand		"^\s*ping"
syn match	yamahaCommand		"^\s*ping6"
syn match	yamahaCommand		"^\s*pki certificate file"
syn match	yamahaCommand		"^\s*pki crl file"
syn match	yamahaCommand		"^\s*pp always-on"
syn match	yamahaCommand		"^\s*pp auth accept"
syn match	yamahaCommand		"^\s*pp auth multi connect prohibit"
syn match	yamahaCommand		"^\s*pp auth myname"
syn match	yamahaCommand		"^\s*pp auth request"
syn match	yamahaCommand		"^\s*pp auth username"
syn match	yamahaCommand		"^\s*pp backup"
syn match	yamahaCommand		"^\s*pp backup recovery time"
syn match	yamahaCommand		"^\s*pp bind"
syn match	yamahaCommand		"^\s*pp disable"
syn match	yamahaCommand		"^\s*pp enable"
syn match	yamahaCommand		"^\s*pp keepalive interval"
syn match	yamahaCommand		"^\s*pp keepalive log"
syn match	yamahaCommand		"^\s*pp keepalive use"
syn match	yamahaCommand		"^\s*pp name"
syn match	yamahaCommand		"^\s*pp select"
syn match	yamahaCommand		"^\s*ppp ccp maxconfigure"
syn match	yamahaCommand		"^\s*ppp ccp maxfailure"
syn match	yamahaCommand		"^\s*ppp ccp maxterminate"
syn match	yamahaCommand		"^\s*ppp ccp no-encryption"
syn match	yamahaCommand		"^\s*ppp ccp restart"
syn match	yamahaCommand		"^\s*ppp ccp type"
syn match	yamahaCommand		"^\s*ppp chap maxchallenge"
syn match	yamahaCommand		"^\s*ppp chap restart"
syn match	yamahaCommand		"^\s*ppp ipcp ipaddress"
syn match	yamahaCommand		"^\s*ppp ipcp maxconfigure"
syn match	yamahaCommand		"^\s*ppp ipcp maxfailure"
syn match	yamahaCommand		"^\s*ppp ipcp maxterminate"
syn match	yamahaCommand		"^\s*ppp ipcp msext"
syn match	yamahaCommand		"^\s*ppp ipcp remote address check"
syn match	yamahaCommand		"^\s*ppp ipcp restart"
syn match	yamahaCommand		"^\s*ppp ipcp vjc"
syn match	yamahaCommand		"^\s*ppp ipv6cp use"
syn match	yamahaCommand		"^\s*ppp lcp accm"
syn match	yamahaCommand		"^\s*ppp lcp acfc"
syn match	yamahaCommand		"^\s*ppp lcp magicnumber"
syn match	yamahaCommand		"^\s*ppp lcp maxconfigure"
syn match	yamahaCommand		"^\s*ppp lcp maxfailure"
syn match	yamahaCommand		"^\s*ppp lcp maxterminate"
syn match	yamahaCommand		"^\s*ppp lcp mru"
syn match	yamahaCommand		"^\s*ppp lcp pfc"
syn match	yamahaCommand		"^\s*ppp lcp restart"
syn match	yamahaCommand		"^\s*ppp lcp silent"
syn match	yamahaCommand		"^\s*ppp mscbcp maxretry"
syn match	yamahaCommand		"^\s*ppp mscbcp restart"
syn match	yamahaCommand		"^\s*ppp pap maxauthreq"
syn match	yamahaCommand		"^\s*ppp pap restart"
syn match	yamahaCommand		"^\s*pppoe access concentrator"
syn match	yamahaCommand		"^\s*pppoe auto connect"
syn match	yamahaCommand		"^\s*pppoe auto disconnect"
syn match	yamahaCommand		"^\s*pppoe call prohibit"
syn match	yamahaCommand		"^\s*pppoe disconnect time"
syn match	yamahaCommand		"^\s*pppoe invalid-session forced close"
syn match	yamahaCommand		"^\s*pppoe padi maxretry"
syn match	yamahaCommand		"^\s*pppoe padi restart"
syn match	yamahaCommand		"^\s*pppoe padr maxretry"
syn match	yamahaCommand		"^\s*pppoe padr restart"
syn match	yamahaCommand		"^\s*pppoe service-name"
syn match	yamahaCommand		"^\s*pppoe tcp mss limit"
syn match	yamahaCommand		"^\s*pppoe use"
syn match	yamahaCommand		"^\s*pptp hostname"
syn match	yamahaCommand		"^\s*pptp keepalive interval"
syn match	yamahaCommand		"^\s*pptp keepalive log"
syn match	yamahaCommand		"^\s*pptp keepalive use"
syn match	yamahaCommand		"^\s*pptp service"
syn match	yamahaCommand		"^\s*pptp service type"
syn match	yamahaCommand		"^\s*pptp syslog"
syn match	yamahaCommand		"^\s*pptp tunnel disconnect time"
syn match	yamahaCommand		"^\s*pptp window size"
syn match	yamahaCommand		"^\s*provider auto connect forced disable"
syn match	yamahaCommand		"^\s*provider dns server"
syn match	yamahaCommand		"^\s*provider dns server pp"
syn match	yamahaCommand		"^\s*provider filter routing"
syn match	yamahaCommand		"^\s*provider ipv6 connect pp"
syn match	yamahaCommand		"^\s*provider lan[1-9] name"
syn match	yamahaCommand		"^\s*provider ntp server"
syn match	yamahaCommand		"^\s*provider ntpdate"
syn match	yamahaCommand		"^\s*provider pp bind"
syn match	yamahaCommand		"^\s*provider select"
syn match	yamahaCommand		"^\s*provider set"
syn match	yamahaCommand		"^\s*provider type"
syn match	yamahaCommand		"^\s*provider wan1 bind"
syn match	yamahaCommand		"^\s*provider wan1 dns server"
syn match	yamahaCommand		"^\s*provider wan1 name"
syn match	yamahaCommand		"^\s*provider .* bind"
syn match	yamahaCommand		"^\s*provider .* dns server"
syn match	yamahaCommand		"^\s*provider .* name"
syn match	yamahaCommand		"^\s*queue class filter"
syn match	yamahaCommand		"^\s*queue pp class filter list"
syn match	yamahaCommand		"^\s*queue pp default class"
syn match	yamahaCommand		"^\s*queue pp length"
syn match	yamahaCommand		"^\s*queue pp type"
syn match	yamahaCommand		"^\s*queue tunnel class filter list"
syn match	yamahaCommand		"^\s*queue wan1 class control"
syn match	yamahaCommand		"^\s*queue wan1 class filter list"
syn match	yamahaCommand		"^\s*queue wan1 class property"
syn match	yamahaCommand		"^\s*queue wan1 default class"
syn match	yamahaCommand		"^\s*queue wan1 length"
syn match	yamahaCommand		"^\s*queue wan1 type"
syn match	yamahaCommand		"^\s*queue .* class control"
syn match	yamahaCommand		"^\s*queue .* class filter list"
syn match	yamahaCommand		"^\s*queue .* class property"
syn match	yamahaCommand		"^\s*queue .* default class"
syn match	yamahaCommand		"^\s*queue .* length"
syn match	yamahaCommand		"^\s*queue .* type"
syn match	yamahaCommand		"^\s*quit"
syn match	yamahaCommand		"^\s*radius account"
syn match	yamahaCommand		"^\s*radius account port"
syn match	yamahaCommand		"^\s*radius account server"
syn match	yamahaCommand		"^\s*radius auth"
syn match	yamahaCommand		"^\s*radius auth port"
syn match	yamahaCommand		"^\s*radius auth server"
syn match	yamahaCommand		"^\s*radius retry"
syn match	yamahaCommand		"^\s*radius secret"
syn match	yamahaCommand		"^\s*radius server"
syn match	yamahaCommand		"^\s*rdate"
syn match	yamahaCommand		"^\s*remote setup accept"
syn match	yamahaCommand		"^\s*rename"
syn match	yamahaCommand		"^\s*restart"
syn match	yamahaCommand		"^\s*rip filter rule"
syn match	yamahaCommand		"^\s*rip preference"
syn match	yamahaCommand		"^\s*rip timer"
syn match	yamahaCommand		"^\s*rip use"
syn match	yamahaCommand		"^\s*rotate external-memory syslog"
syn match	yamahaCommand		"^\s*rtfs format"
syn match	yamahaCommand		"^\s*rtfs garbage-collect"
syn match	yamahaCommand		"^\s*save"
syn match	yamahaCommand		"^\s*schedule at"
syn match	yamahaCommand		"^\s*scp"
syn match	yamahaCommand		"^\s*sd use"
syn match	yamahaCommand		"^\s*security class"
syn match	yamahaCommand		"^\s*set"
syn match	yamahaCommand		"^\s*set-default-config"
syn match	yamahaCommand		"^\s*sftpd host"
syn match	yamahaCommand		"^\s*show account"
syn match	yamahaCommand		"^\s*show account mobile"
syn match	yamahaCommand		"^\s*show account ngn data"
syn match	yamahaCommand		"^\s*show account pp"
syn match	yamahaCommand		"^\s*show arp"
syn match	yamahaCommand		"^\s*show bridge learning"
syn match	yamahaCommand		"^\s*show command"
syn match	yamahaCommand		"^\s*show config"
syn match	yamahaCommand		"^\s*show config list"
syn match	yamahaCommand		"^\s*show config pp"
syn match	yamahaCommand		"^\s*show config tunnel"
syn match	yamahaCommand		"^\s*show dns cache"
syn match	yamahaCommand		"^\s*show environment"
syn match	yamahaCommand		"^\s*show exec list"
syn match	yamahaCommand		"^\s*show file list"
syn match	yamahaCommand		"^\s*show history"
syn match	yamahaCommand		"^\s*show ip connection"
syn match	yamahaCommand		"^\s*show ip intrusion detection"
syn match	yamahaCommand		"^\s*show ip rip table"
syn match	yamahaCommand		"^\s*show ip route"
syn match	yamahaCommand		"^\s*show ip secure filter loopback1"
syn match	yamahaCommand		"^\s*show ip secure filter loopback2"
syn match	yamahaCommand		"^\s*show ip secure filter loopback3"
syn match	yamahaCommand		"^\s*show ip secure filter loopback4"
syn match	yamahaCommand		"^\s*show ip secure filter loopback5"
syn match	yamahaCommand		"^\s*show ip secure filter loopback6"
syn match	yamahaCommand		"^\s*show ip secure filter loopback7"
syn match	yamahaCommand		"^\s*show ip secure filter loopback8"
syn match	yamahaCommand		"^\s*show ip secure filter loopback9"
syn match	yamahaCommand		"^\s*show ip secure filter null"
syn match	yamahaCommand		"^\s*show ip secure filter pp"
syn match	yamahaCommand		"^\s*show ip secure filter tunnel"
syn match	yamahaCommand		"^\s*show ip secure filter wan1"
syn match	yamahaCommand		"^\s*show ip secure filter"
syn match	yamahaCommand		"^\s*show ipsec sa"
syn match	yamahaCommand		"^\s*show ipv6 address"
syn match	yamahaCommand		"^\s*show ipv6 connection"
syn match	yamahaCommand		"^\s*show ipv6 mroute fib"
syn match	yamahaCommand		"^\s*show ipv6 neighbor cache"
syn match	yamahaCommand		"^\s*show ipv6 ospf"
syn match	yamahaCommand		"^\s*show ipv6 rip table"
syn match	yamahaCommand		"^\s*show ipv6 route"
syn match	yamahaCommand		"^\s*show log"
syn match	yamahaCommand		"^\s*show nat descriptor address"
syn match	yamahaCommand		"^\s*show nat descriptor interface address pp"
syn match	yamahaCommand		"^\s*show nat descriptor interface address tunnel"
syn match	yamahaCommand		"^\s*show nat descriptor interface address wan1"
syn match	yamahaCommand		"^\s*show nat descriptor interface address"
syn match	yamahaCommand		"^\s*show nat descriptor interface bind pp"
syn match	yamahaCommand		"^\s*show nat descriptor interface bind tunnel"
syn match	yamahaCommand		"^\s*show nat descriptor interface bind wan1"
syn match	yamahaCommand		"^\s*show nat descriptor interface bind"
syn match	yamahaCommand		"^\s*show nat descriptor masquerade port"
syn match	yamahaCommand		"^\s*show pki certificate summary"
syn match	yamahaCommand		"^\s*show pki crl"
syn match	yamahaCommand		"^\s*show pp connect time"
syn match	yamahaCommand		"^\s*show sshd public key"
syn match	yamahaCommand		"^\s*show status backup"
syn match	yamahaCommand		"^\s*show status bgp"
syn match	yamahaCommand		"^\s*show status boot"
syn match	yamahaCommand		"^\s*show status boot all"
syn match	yamahaCommand		"^\s*show status boot list"
syn match	yamahaCommand		"^\s*show status cooperation"
syn match	yamahaCommand		"^\s*show status dhcp"
syn match	yamahaCommand		"^\s*show status dhcpc"
syn match	yamahaCommand		"^\s*show status ethernet"
syn match	yamahaCommand		"^\s*show status external-memory"
syn match	yamahaCommand		"^\s*show status heartbeat"
syn match	yamahaCommand		"^\s*show status heartbeat2"
syn match	yamahaCommand		"^\s*show status ip keepalive"
syn match	yamahaCommand		"^\s*show status ipv6 dhcp"
syn match	yamahaCommand		"^\s*show status ipv6 mld"
syn match	yamahaCommand		"^\s*show status l2tp"
syn match	yamahaCommand		"^\s*show status l2tp tunnel"
syn match	yamahaCommand		"^\s*show status lua"
syn match	yamahaCommand		"^\s*show status mail service"
syn match	yamahaCommand		"^\s*show status mobile signal-strength"
syn match	yamahaCommand		"^\s*show status netvolante-dns pp"
syn match	yamahaCommand		"^\s*show status netvolante-dns wan1"
syn match	yamahaCommand		"^\s*show status netvolante-dns"
syn match	yamahaCommand		"^\s*show status ngn"
syn match	yamahaCommand		"^\s*show status ospf"
syn match	yamahaCommand		"^\s*show status packet-buffer"
syn match	yamahaCommand		"^\s*show status pp"
syn match	yamahaCommand		"^\s*show status pptp"
syn match	yamahaCommand		"^\s*show status qos"
syn match	yamahaCommand		"^\s*show status remote setup"
syn match	yamahaCommand		"^\s*show status rtfs"
syn match	yamahaCommand		"^\s*show status sd"
syn match	yamahaCommand		"^\s*show status switch control"
syn match	yamahaCommand		"^\s*show status switch control route backup"
syn match	yamahaCommand		"^\s*show status switching-hub macaddress"
syn match	yamahaCommand		"^\s*show status tunnel"
syn match	yamahaCommand		"^\s*show status upnp"
syn match	yamahaCommand		"^\s*show status usbhost"
syn match	yamahaCommand		"^\s*show status usbhost modem"
syn match	yamahaCommand		"^\s*show status user"
syn match	yamahaCommand		"^\s*show status vlan"
syn match	yamahaCommand		"^\s*show status vrrp"
syn match	yamahaCommand		"^\s*show status wan1"
syn match	yamahaCommand		"^\s*show status"
syn match	yamahaCommand		"^\s*show techinfo"
syn match	yamahaCommand		"^\s*show url filter"
syn match	yamahaCommand		"^\s*sip 100rel"
syn match	yamahaCommand		"^\s*sip arrive address check"
syn match	yamahaCommand		"^\s*sip arrive ringing p-n-uatype"
syn match	yamahaCommand		"^\s*sip arrive session timer method"
syn match	yamahaCommand		"^\s*sip arrive session timer refresher"
syn match	yamahaCommand		"^\s*sip codec permit"
syn match	yamahaCommand		"^\s*sip ip protocol"
syn match	yamahaCommand		"^\s*sip log"
syn match	yamahaCommand		"^\s*sip outer address"
syn match	yamahaCommand		"^\s*sip response code busy"
syn match	yamahaCommand		"^\s*sip session timer"
syn match	yamahaCommand		"^\s*sip use"
syn match	yamahaCommand		"^\s*sip user agent"
syn match	yamahaCommand		"^\s*snmp community read-only"
syn match	yamahaCommand		"^\s*snmp community read-write"
syn match	yamahaCommand		"^\s*snmp display ipcp force"
syn match	yamahaCommand		"^\s*snmp host"
syn match	yamahaCommand		"^\s*snmp ifindex switch static index"
syn match	yamahaCommand		"^\s*snmp local address"
syn match	yamahaCommand		"^\s*snmp syscontact"
syn match	yamahaCommand		"^\s*snmp syslocation"
syn match	yamahaCommand		"^\s*snmp sysname"
syn match	yamahaCommand		"^\s*snmp trap community"
syn match	yamahaCommand		"^\s*snmp trap enable snmp"
syn match	yamahaCommand		"^\s*snmp trap enable switch"
syn match	yamahaCommand		"^\s*snmp trap enable switch common"
syn match	yamahaCommand		"^\s*snmp trap host"
syn match	yamahaCommand		"^\s*snmp trap link-updown separate-l2switch-port lan1"
syn match	yamahaCommand		"^\s*snmp trap mobile signal-strength"
syn match	yamahaCommand		"^\s*snmp trap send linkdown pp"
syn match	yamahaCommand		"^\s*snmp trap send linkdown tunnel"
syn match	yamahaCommand		"^\s*snmp trap send linkdown wan1"
syn match	yamahaCommand		"^\s*snmp trap send linkdown"
syn match	yamahaCommand		"^\s*snmp yrifppdisplayatmib2"
syn match	yamahaCommand		"^\s*snmp yrifswitchdisplayatmib2"
syn match	yamahaCommand		"^\s*snmp yriftunneldisplayatmib2"
syn match	yamahaCommand		"^\s*snmp yrswindex switch static index"
syn match	yamahaCommand		"^\s*snmpv2c community read-only"
syn match	yamahaCommand		"^\s*snmpv2c community read-write"
syn match	yamahaCommand		"^\s*snmpv2c host"
syn match	yamahaCommand		"^\s*snmpv2c trap community"
syn match	yamahaCommand		"^\s*snmpv2c trap host"
syn match	yamahaCommand		"^\s*snmpv3 context name"
syn match	yamahaCommand		"^\s*snmpv3 engine id"
syn match	yamahaCommand		"^\s*snmpv3 host"
syn match	yamahaCommand		"^\s*snmpv3 trap host"
syn match	yamahaCommand		"^\s*snmpv3 usm user"
syn match	yamahaCommand		"^\s*snmpv3 vacm access"
syn match	yamahaCommand		"^\s*snmpv3 vacm view"
syn match	yamahaCommand		"^\s*sntpd host"
syn match	yamahaCommand		"^\s*sntpd service"
syn match	yamahaCommand		"^\s*speed wan1"
syn match	yamahaCommand		"^\s*speed"
syn match	yamahaCommand		"^\s*ssh"
syn match	yamahaCommand		"^\s*ssh encrypt algorithm"
syn match	yamahaCommand		"^\s*ssh known hosts"
syn match	yamahaCommand		"^\s*sshd client alive"
syn match	yamahaCommand		"^\s*sshd encrypt algorithm"
syn match	yamahaCommand		"^\s*sshd host"
syn match	yamahaCommand		"^\s*sshd host key generate"
syn match	yamahaCommand		"^\s*sshd listen"
syn match	yamahaCommand		"^\s*sshd service"
syn match	yamahaCommand		"^\s*sshd session"
syn match	yamahaCommand		"^\s*statistics cpu"
syn match	yamahaCommand		"^\s*statistics memory"
syn match	yamahaCommand		"^\s*switch control firmware upload go"
syn match	yamahaCommand		"^\s*switch control function default"
syn match	yamahaCommand		"^\s*switch control function execute clear-counter"
syn match	yamahaCommand		"^\s*switch control function execute clear-macaddress-table"
syn match	yamahaCommand		"^\s*switch control function execute reset-loopdetect"
syn match	yamahaCommand		"^\s*switch control function execute restart"
syn match	yamahaCommand		"^\s*switch control function execute restart-poe-supply"
syn match	yamahaCommand		"^\s*switch control function get boot-rom-version"
syn match	yamahaCommand		"^\s*switch control function get counter-frame-rx-type"
syn match	yamahaCommand		"^\s*switch control function get counter-frame-tx-type"
syn match	yamahaCommand		"^\s*switch control function get energy-saving"
syn match	yamahaCommand		"^\s*switch control function get firmware-revision"
syn match	yamahaCommand		"^\s*switch control function get led-brightness"
syn match	yamahaCommand		"^\s*switch control function get loopdetect-count"
syn match	yamahaCommand		"^\s*switch control function get loopdetect-linkdown"
syn match	yamahaCommand		"^\s*switch control function get loopdetect-port-use"
syn match	yamahaCommand		"^\s*switch control function get loopdetect-recovery-timer"
syn match	yamahaCommand		"^\s*switch control function get loopdetect-time"
syn match	yamahaCommand		"^\s*switch control function get loopdetect-use-control-packet"
syn match	yamahaCommand		"^\s*loopdetect-use-control-packetの設定値を取得します"
syn match	yamahaCommand		"^\s*switch control function get macaddress-aging"
syn match	yamahaCommand		"^\s*switch control function get macaddress-aging-timer"
syn match	yamahaCommand		"^\s*switch control function get mirroring-dest"
syn match	yamahaCommand		"^\s*switch control function get mirroring-src-rx"
syn match	yamahaCommand		"^\s*switch control function get mirroring-src-tx"
syn match	yamahaCommand		"^\s*switch control function get mirroring-use"
syn match	yamahaCommand		"^\s*switch control function get model-name"
syn match	yamahaCommand		"^\s*switch control function get poe-class"
syn match	yamahaCommand		"^\s*switch control function get port-auto-crossover"
syn match	yamahaCommand		"^\s*switch control function get port-blocking-control-packet"
syn match	yamahaCommand		"^\s*switch control function get port-blocking-data-packet"
syn match	yamahaCommand		"^\s*switch control function get port-flow-control"
syn match	yamahaCommand		"^\s*switch control function get port-speed"
syn match	yamahaCommand		"^\s*switch control function get port-speed-downshift"
syn match	yamahaCommand		"^\s*switch control function get port-use"
syn match	yamahaCommand		"^\s*switch control function get qos-dscp-remark-class"
syn match	yamahaCommand		"^\s*switch control function get qos-dscp-remark-type"
syn match	yamahaCommand		"^\s*switch control function get qos-policing-speed"
syn match	yamahaCommand		"^\s*switch control function get qos-policing-use"
syn match	yamahaCommand		"^\s*switch control function get qos-shaping-speed"
syn match	yamahaCommand		"^\s*switch control function get qos-shaping-use"
syn match	yamahaCommand		"^\s*switch control function get qos-speed-unit"
syn match	yamahaCommand		"^\s*switch control function get serial-number"
syn match	yamahaCommand		"^\s*switch control function get status-counter-frame-rx"
syn match	yamahaCommand		"^\s*switch control function get status-counter-frame-tx"
syn match	yamahaCommand		"^\s*switch control function get status-counter-octet-rx"
syn match	yamahaCommand		"^\s*switch control function get status-counter-octet-tx"
syn match	yamahaCommand		"^\s*switch control function get status-fan"
syn match	yamahaCommand		"^\s*switch control function get status-fan-rpm"
syn match	yamahaCommand		"^\s*switch control function get status-led-mode"
syn match	yamahaCommand		"^\s*switch control function get status-loopdetect-port"
syn match	yamahaCommand		"^\s*switch control function get status-loopdetect-recovery-timer"
syn match	yamahaCommand		"^\s*switch control function get status-macaddress-addr"
syn match	yamahaCommand		"^\s*switch control function get status-macaddress-port"
syn match	yamahaCommand		"^\s*switch control function get status-poe-detect-class"
syn match	yamahaCommand		"^\s*switch control function get status-poe-state"
syn match	yamahaCommand		"^\s*switch control function get status-poe-supply"
syn match	yamahaCommand		"^\s*switch control function get status-poe-temperature"
syn match	yamahaCommand		"^\s*switch control function get status-port-speed"
syn match	yamahaCommand		"^\s*switch control function get system-macaddress"
syn match	yamahaCommand		"^\s*switch control function get system-name"
syn match	yamahaCommand		"^\s*switch control function get system-uptime"
syn match	yamahaCommand		"^\s*switch control function get vlan-access"
syn match	yamahaCommand		"^\s*switch control function get vlan-id"
syn match	yamahaCommand		"^\s*switch control function get vlan-multiple"
syn match	yamahaCommand		"^\s*switch control function get vlan-multiple-use"
syn match	yamahaCommand		"^\s*switch control function get vlan-port-mode"
syn match	yamahaCommand		"^\s*switch control function get vlan-trunk"
syn match	yamahaCommand		"^\s*switch control function set counter-frame-rx-type"
syn match	yamahaCommand		"^\s*switch control function set counter-frame-tx-type"
syn match	yamahaCommand		"^\s*switch control function set energy-saving"
syn match	yamahaCommand		"^\s*switch control function set led-brightness"
syn match	yamahaCommand		"^\s*switch control function set loopdetect-count"
syn match	yamahaCommand		"^\s*switch control function set loopdetect-linkdown"
syn match	yamahaCommand		"^\s*switch control function set loopdetect-port-use"
syn match	yamahaCommand		"^\s*switch control function set loopdetect-recovery-timer"
syn match	yamahaCommand		"^\s*switch control function set loopdetect-time"
syn match	yamahaCommand		"^\s*switch control function set loopdetect-use-control-packet"
syn match	yamahaCommand		"^\s*switch control function set macaddress-aging"
syn match	yamahaCommand		"^\s*switch control function set macaddress-aging-timer"
syn match	yamahaCommand		"^\s*switch control function set mirroring-dest"
syn match	yamahaCommand		"^\s*switch control function set mirroring-src-rx"
syn match	yamahaCommand		"^\s*switch control function set mirroring-src-tx"
syn match	yamahaCommand		"^\s*switch control function set mirroring-use"
syn match	yamahaCommand		"^\s*switch control function set poe-class"
syn match	yamahaCommand		"^\s*switch control function set port-auto-crossover"
syn match	yamahaCommand		"^\s*switch control function set port-blocking-control-packet"
syn match	yamahaCommand		"^\s*switch control function set port-blocking-data-packet"
syn match	yamahaCommand		"^\s*switch control function set port-flow-control"
syn match	yamahaCommand		"^\s*switch control function set port-speed"
syn match	yamahaCommand		"^\s*switch control function set port-speed-downshift"
syn match	yamahaCommand		"^\s*switch control function set port-use"
syn match	yamahaCommand		"^\s*switch control function set qos-dscp-remark-class"
syn match	yamahaCommand		"^\s*switch control function set qos-dscp-remark-type"
syn match	yamahaCommand		"^\s*switch control function set qos-policing-speed"
syn match	yamahaCommand		"^\s*switch control function set qos-policing-use"
syn match	yamahaCommand		"^\s*switch control function set qos-shaping-speed"
syn match	yamahaCommand		"^\s*switch control function set qos-shaping-use"
syn match	yamahaCommand		"^\s*switch control function set qos-speed-unit"
syn match	yamahaCommand		"^\s*switch control function set system-name"
syn match	yamahaCommand		"^\s*switch control function set vlan-access"
syn match	yamahaCommand		"^\s*switch control function set vlan-id"
syn match	yamahaCommand		"^\s*switch control function set vlan-multiple"
syn match	yamahaCommand		"^\s*switch control function set vlan-multiple-use"
syn match	yamahaCommand		"^\s*switch control function set vlan-port-mode"
syn match	yamahaCommand		"^\s*switch control function set vlan-trunk"
syn match	yamahaCommand		"^\s*switch control route backup"
syn match	yamahaCommand		"^\s*switch control use"
syn match	yamahaCommand		"^\s*switch control watch interval"
syn match	yamahaCommand		"^\s*switch select"
syn match	yamahaCommand		"^\s*syslog debug"
syn match	yamahaCommand		"^\s*syslog execute command"
syn match	yamahaCommand		"^\s*syslog facility"
syn match	yamahaCommand		"^\s*syslog host"
syn match	yamahaCommand		"^\s*syslog info"
syn match	yamahaCommand		"^\s*syslog local address"
syn match	yamahaCommand		"^\s*syslog notice"
syn match	yamahaCommand		"^\s*syslog srcport"
syn match	yamahaCommand		"^\s*system led brightness"
syn match	yamahaCommand		"^\s*system packet-buffer"
syn match	yamahaCommand		"^\s*tcp log"
syn match	yamahaCommand		"^\s*tcp session limit"
syn match	yamahaCommand		"^\s*telnet"
syn match	yamahaCommand		"^\s*telnetd host"
syn match	yamahaCommand		"^\s*telnetd listen"
syn match	yamahaCommand		"^\s*telnetd service"
syn match	yamahaCommand		"^\s*telnetd session"
syn match	yamahaCommand		"^\s*terminate lua"
syn match	yamahaCommand		"^\s*terminate lua file"
syn match	yamahaCommand		"^\s*tftp host"
syn match	yamahaCommand		"^\s*time"
syn match	yamahaCommand		"^\s*timezone"
syn match	yamahaCommand		"^\s*traceroute"
syn match	yamahaCommand		"^\s*traceroute6"
syn match	yamahaCommand		"^\s*tunnel backup"
syn match	yamahaCommand		"^\s*tunnel disable"
syn match	yamahaCommand		"^\s*tunnel enable"
syn match	yamahaCommand		"^\s*tunnel encapsulation"
syn match	yamahaCommand		"^\s*tunnel endpoint address"
syn match	yamahaCommand		"^\s*tunnel endpoint name"
syn match	yamahaCommand		"^\s*tunnel name"
syn match	yamahaCommand		"^\s*tunnel ngn arrive permit"
syn match	yamahaCommand		"^\s*tunnel ngn bandwidth"
syn match	yamahaCommand		"^\s*tunnel ngn call permit"
syn match	yamahaCommand		"^\s*tunnel ngn disconnect time"
syn match	yamahaCommand		"^\s*tunnel ngn fallback"
syn match	yamahaCommand		"^\s*tunnel ngn interface"
syn match	yamahaCommand		"^\s*tunnel ngn radius auth"
syn match	yamahaCommand		"^\s*tunnel select"
syn match	yamahaCommand		"^\s*tunnel template"
syn match	yamahaCommand		"^\s*upnp external address refer"
syn match	yamahaCommand		"^\s*upnp port mapping timer"
syn match	yamahaCommand		"^\s*upnp port mapping timer type"
syn match	yamahaCommand		"^\s*upnp syslog"
syn match	yamahaCommand		"^\s*upnp use"
syn match	yamahaCommand		"^\s*url filter"
syn match	yamahaCommand		"^\s*url filter log"
syn match	yamahaCommand		"^\s*url filter port"
syn match	yamahaCommand		"^\s*url filter reject"
syn match	yamahaCommand		"^\s*url filter use"
syn match	yamahaCommand		"^\s*url pp filter"
syn match	yamahaCommand		"^\s*url tunnel filter"
syn match	yamahaCommand		"^\s*url wan1 filter"
syn match	yamahaCommand		"^\s*url .* filter"
syn match	yamahaCommand		"^\s*usbhost modem flow control"
syn match	yamahaCommand		"^\s*usbhost modem initialize"
syn match	yamahaCommand		"^\s*usbhost overcurrent duration"
syn match	yamahaCommand		"^\s*usbhost use"
syn match	yamahaCommand		"^\s*user attribute"
syn match	yamahaCommand		"^\s*vlan port mapping"
syn match	yamahaCommand		"^\s*vlan .* 802.1q"
syn match	yamahaCommand		"^\s*wan1 access limit connection length"
syn match	yamahaCommand		"^\s*wan1 access limit connection time"
syn match	yamahaCommand		"^\s*wan1 access limit duration"
syn match	yamahaCommand		"^\s*wan1 access limit length"
syn match	yamahaCommand		"^\s*wan1 access limit time"
syn match	yamahaCommand		"^\s*wan1 access-point name"
syn match	yamahaCommand		"^\s*wan1 always-on"
syn match	yamahaCommand		"^\s*wan1 auth myname"
syn match	yamahaCommand		"^\s*wan1 auto connect"
syn match	yamahaCommand		"^\s*wan1 bind"
syn match	yamahaCommand		"^\s*wan1 disconnect input time"
syn match	yamahaCommand		"^\s*wan1 disconnect output time"
syn match	yamahaCommand		"^\s*wan1 disconnect time"
syn match	yamahaCommand		"^\s*wins server"
syn match	yamahaCommand		"^\s*wol send"




hi link yamahaNumber	Number
hi link yamahaTime		Number
hi link yamahaString	String
hi link yamahaIPv4		Number
hi link yamahaSubnet	Number
hi link yamahaEmail		String
hi link yamahaURL		String
hi link yamahaBind		Number
hi link yamahaTunnel	Function
hi link yamahaVlan		Function
hi link yamahaPP		Function
hi link yamahaBRI		Function
hi link yamahaPRI		Function
hi link yamahaBridge	Function
hi link yamahaUSB		Function
hi link yamahaComment	Comment
hi link yamahaCommand	Statement
hi link yamahaEqual		Statement
hi link yamahaBuiltin	Function
hi link yamahaSplitinto	Function
hi link yamahaPort		Function
hi link yamahaBandwidth	Number
